/**
 * TAVI Workup Types - Live Document System
 *
 * Defines data structures for persistent TAVI workup management with Notion sync.
 * Workups are stored locally (chrome.storage.local) with optional Notion status sync.
 */

import type { TAVIWorkupStructuredSections, ValidationResult, TAVIExtractedData, TAVIWorkupCTMeasurements } from './medical.types';
import type { DicomSnapshot } from './dicom.types';

/**
 * Core workup item - represents a single TAVI patient workup
 * Combines Notion metadata + local workup data + EMR extracts
 */
export interface TAVIWorkupItem {
  // === IDENTITY ===
  id: string; // UUID generated by extension

  // === NOTION SYNC (one-way status push) ===
  notionPageId?: string; // Notion page ID if linked
  notionStatus?: 'pending' | 'in-progress' | 'presented'; // Last synced status
  notionUrl?: string; // Deep link to Notion page
  lastSyncedAt?: number; // Unix timestamp of last Notion sync

  // === NOTION DATABASE FIELDS (from schema) ===
  patient: string; // Patient name (Notion title field)
  referralDate?: string; // YYYY-MM-DD
  referrer?: string; // Referring doctor
  location?: string; // Hospital/site (e.g., "Cabrini", "Peninsula")
  procedureDate?: string; // YYYY-MM-DD
  readyToPresent?: boolean; // Ready for presentation flag
  category?: string; // Workup category (e.g., "Elective", "Urgent")
  datePresented?: string; // YYYY-MM-DD when presented

  // === WORKUP DATA (existing TAVI structure) ===
  structuredSections: TAVIWorkupStructuredSections; // 12 narrative sections

  // === STRUCTURED CT MEASUREMENTS ===
  ctMeasurements?: TAVIWorkupCTMeasurements; // Numeric valve sizing, access vessels, etc.

  // === EMR AUTO-EXTRACTED DATA (cached from Xestro) ===
  emrBackground?: string; // Auto-pulled from EMR Background field
  emrInvestigations?: string; // Auto-pulled from EMR Investigations field
  emrMedications?: string; // Auto-pulled from EMR Medications field
  emrLastExtracted?: number; // Unix timestamp of last EMR extraction

  // === METADATA ===
  createdAt: number; // Unix timestamp of creation
  lastUpdatedAt: number; // Unix timestamp of last local update
  completionPercentage: number; // 0-100 based on filled sections
  status: 'draft' | 'ready' | 'presented'; // Local status (maps to Notion status)

  // === VALIDATION & EXTRACTION ===
  validationResult?: ValidationResult; // From validation checkpoint (if applicable)
  extractedData?: TAVIExtractedData; // Regex-extracted valve sizing, etc.

  // === VERSION HISTORY (optional, Phase 2+) ===
  versionHistory?: TAVIWorkupVersion[];

  // === DICOM SNAPSHOTS (Phase 8) ===
  snapshots?: DicomSnapshot[]; // Captured CT viewport images with metadata
}

/**
 * Version snapshot for undo/redo functionality
 */
export interface TAVIWorkupVersion {
  timestamp: number; // Unix timestamp
  snapshot: TAVIWorkupStructuredSections; // Full section snapshot
  changeDescription: string; // Human-readable description (e.g., "Dictated CT measurements")
}

/**
 * Notion patient data (fetched from Structural Workup database)
 * Used for importing new workups from Notion list
 */
export interface NotionTAVIPatient {
  notionPageId: string; // Notion page ID
  notionUrl: string; // Deep link to Notion page
  patient: string; // Patient name
  referralDate?: string; // YYYY-MM-DD
  referrer?: string;
  location?: string;
  procedureDate?: string;
  status?: string; // Notion status field value
  category?: string;
  readyToPresent?: boolean;
  lastEditedTime: number; // Unix timestamp from Notion
}

/**
 * Helper to create empty structured sections
 * NOTE: CT data is NOT in structuredSections - it lives in TAVIWorkupItem.ctMeasurements
 */
export function createEmptyStructuredSections(): TAVIWorkupStructuredSections {
  return {
    patient: { content: '', missing: [] },
    clinical: { content: '', missing: [] },
    laboratory: { content: '', missing: [] },
    ecg: { content: '', missing: [] },
    background: { content: '', missing: [] },
    medications: { content: '', missing: [] },
    social_history: { content: '', missing: [] },
    investigations: { content: '', missing: [] },
    echocardiography: { content: '', missing: [] },
    // enhanced_ct REMOVED - CT data now lives in TAVIWorkupItem.ctMeasurements
    procedure_planning: { content: '', missing: [] },
    alerts: { content: '', missing: [], pre_anaesthetic_review_text: '', pre_anaesthetic_review_json: null },
    missing_summary: { missing_clinical: [], missing_diagnostic: [], missing_measurements: [], completeness_score: '0' }
  };
}

/**
 * Calculate completion percentage based on filled sections
 * NOTE: CT data is tracked separately in TAVIWorkupItem.ctMeasurements (not in structuredSections)
 */
export function calculateCompletion(sections: TAVIWorkupStructuredSections): number {
  const totalSections = 10; // Exclude missing_summary (and enhanced_ct removed)
  let completed = 0;

  Object.keys(sections).forEach(key => {
    if (key === 'missing_summary') return;
    const section = sections[key as keyof TAVIWorkupStructuredSections];
    if (section && 'content' in section && section.content && section.content !== 'Not provided') {
      completed++;
    }
  });

  return Math.round((completed / totalSections) * 100);
}
